name: ibd_scan
channels:
 - conda-forge
 - defaults
dependencies:
 - click=8.0.3
 - colorama=0.4.4
 - numpy=1.22.0
 - pandas=1.4.0
 - python-dateutil=2.8.2
 - pytz=2021.3
 - six=1.16.0
 - typer=0.4.0
